### ISSUE TITLE
コーディング修正_1

### ISSUE THREAD

**Issue by 0014ug** [Club-Advance/goodday#10]
・WOMEN pick up itemページ 最下段の「※価格は異なる〜」→トル
・MEN pick up itemページ 最下段の「※価格は異なる〜」→トル
・KIDS TOPページのpick up item画像差し替え→後送
・KIDS Toddler Schoolスライダーのところ過去のものに「NEW」が入ってる
・KIDS Toddler Schoolスライダーのところ、クリックしてくと新しいコーデが消えてしまう？
　（KIDS TOPページから入っていったときは正確に表示されます。説明が難しい…）

以上

**Comment by IKKImt** [comment]
kidsのところもらったaiにnew入ってました〜

**Comment by IKKImt** [comment]
・WOMEN pick up itemページ 最下段の「※価格は異なる〜」→トル
→済み

・MEN pick up itemページ 最下段の「※価格は異なる〜」→トル
→済み

・KIDS TOPページのpick up item画像差し替え→後送
→待ち

・KIDS Toddler Schoolスライダーのところ過去のものに「NEW」が入ってる
→02_kidsのaiに入ってる写真にnewが入っています。

・KIDS Toddler Schoolスライダーのところ、クリックしてくと新しいコーデが消えてしまう？
　（KIDS TOPページから入っていったときは正確に表示されます。説明が難しい…）
→要確認
